# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: octo.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nocto.proto\x12\x04octo\"#\n\x0bOctoRequest\x12\x14\n\x0cjson_message\x18\x01 \x01(\t\"2\n\x0cOctoResponse\x12\x14\n\x0cjson_message\x18\x01 \x01(\t\x12\x0c\n\x04test\x18\x02 \x01(\t\"\x10\n\x0eGetDataRequest2\x85\x01\n\x0eMessageService\x12\x36\n\x0bOctoMessage\x12\x11.octo.OctoRequest\x1a\x12.octo.OctoResponse\"\x00\x12;\n\rGetDataFormat\x12\x14.octo.GetDataRequest\x1a\x12.octo.OctoResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'octo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OCTOREQUEST']._serialized_start=20
  _globals['_OCTOREQUEST']._serialized_end=55
  _globals['_OCTORESPONSE']._serialized_start=57
  _globals['_OCTORESPONSE']._serialized_end=107
  _globals['_GETDATAREQUEST']._serialized_start=109
  _globals['_GETDATAREQUEST']._serialized_end=125
  _globals['_MESSAGESERVICE']._serialized_start=128
  _globals['_MESSAGESERVICE']._serialized_end=261
# @@protoc_insertion_point(module_scope)
